"""
ECS Runtime System for Generated Games

This module provides a complete Entity-Component-System architecture
for games generated by the compiler orchestrator.
"""

from .core.entity import Entity
from .core.component import (
    Component, TransformComponent, VelocityComponent, SpriteComponent,
    CollisionComponent, AnimationComponent, HealthComponent,
    InputComponent, AudioComponent
)
from .core.system import System
from .core.world import World
from .core.event_bus import EventBus, GameEvents

from .systems.input_system import InputSystem
from .systems.physics_system import PhysicsSystem, PlatformerPhysicsSystem
from .systems.collision_system import CollisionSystem
from .systems.animation_system import AnimationSystem
from .systems.audio_system import AudioSystem
from .systems.ui_system import UISystem, HUDSystem
from .systems.scene_manager import SceneManager

__all__ = [
    'Entity', 'Component', 'System', 'World', 'EventBus', 'GameEvents',
    'TransformComponent', 'VelocityComponent', 'SpriteComponent',
    'CollisionComponent', 'AnimationComponent', 'HealthComponent',
    'InputComponent', 'AudioComponent',
    'InputSystem', 'PhysicsSystem', 'PlatformerPhysicsSystem',
    'CollisionSystem', 'AnimationSystem', 'AudioSystem',
    'UISystem', 'HUDSystem', 'SceneManager'
]